overrides:
  - files:
      - "*.java"
    options:
      printWidth: 100
      tabWidth: 4
      useTabs: false
      semi: true
      singleQuote: false
      trailingComma: "none"
      bracketSpacing: false
      arrowParens: "avoid"